<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
		
		DB::table('Pais')->insert([
		['id' => 1	, 'nombre' => 'Afghanistan'							],
		['id' => 2	, 'nombre' => 'Albania'                             ],
		['id' => 3	, 'nombre' => 'Algeria'                             ],
		['id' => 4	, 'nombre' => 'American Samoa'                      ],
		['id' => 5	, 'nombre' => 'Andorra'                             ],
		['id' => 6	, 'nombre' => 'Angola'                              ],
		['id' => 7	, 'nombre' => 'Anguilla'                            ],
		['id' => 8	, 'nombre' => 'Antigua & Barbuda'                   ],
		['id' => 9	, 'nombre' => 'Argentina'                           ],
		['id' => 10	, 'nombre' => 'Armenia'                             ],
		['id' => 11	, 'nombre' => 'Aruba'                               ],
		['id' => 12	, 'nombre' => 'Australia'                           ],
		['id' => 13	, 'nombre' => 'Austria'                             ],
		['id' => 14	, 'nombre' => 'Azerbaijan'                          ],
		['id' => 15	, 'nombre' => 'Bahamas'                             ],
		['id' => 16	, 'nombre' => 'Bahrain'                             ],
		['id' => 17	, 'nombre' => 'Bangladesh'                          ],
		['id' => 18	, 'nombre' => 'Barbados'                            ],
		['id' => 19	, 'nombre' => 'Belarus'                             ],
		['id' => 20	, 'nombre' => 'Belgium'                             ],
		['id' => 21	, 'nombre' => 'Belize'                              ],
		['id' => 22	, 'nombre' => 'Benin'                               ],
		['id' => 23	, 'nombre' => 'Bermuda'                             ],
		['id' => 24	, 'nombre' => 'Bhutan'                              ],
		['id' => 25	, 'nombre' => 'Bolivia'                             ],
		['id' => 26	, 'nombre' => 'Bosnia & Herzegovina'                ],
		['id' => 27	, 'nombre' => 'Botswana'                            ],
		['id' => 28	, 'nombre' => 'Brazil'                              ],
		['id' => 29	, 'nombre' => 'British Virgin Is.'                  ],
		['id' => 30	, 'nombre' => 'Brunei'                              ],
		['id' => 31	, 'nombre' => 'Bulgaria'                            ],
		['id' => 32	, 'nombre' => 'Burkina Faso'                        ],
		['id' => 33	, 'nombre' => 'Burma'                               ],
		['id' => 34	, 'nombre' => 'Burundi'                             ],
		['id' => 35	, 'nombre' => 'Cambodia'                            ],
		['id' => 36	, 'nombre' => 'Cameroon'                            ],
		['id' => 37	, 'nombre' => 'Canada'                              ],
		['id' => 38	, 'nombre' => 'Cape Verde'                          ],
		['id' => 39	, 'nombre' => 'Cayman Islands'                      ],
		['id' => 40	, 'nombre' => 'Central African Rep.'                ],
		['id' => 41	, 'nombre' => 'Chad'                                ],
		['id' => 42	, 'nombre' => 'Chile'                               ],
		['id' => 43	, 'nombre' => 'China'                               ],
		['id' => 44	, 'nombre' => 'Colombia'                            ],
		['id' => 45	, 'nombre' => 'Comoros'                             ],
		['id' => 46	, 'nombre' => 'Congo, Dem. Rep.'                    ],
		['id' => 47	, 'nombre' => 'Congo, Repub. of the'                ],
		['id' => 48	, 'nombre' => 'Cook Islands'                        ],
		['id' => 49	, 'nombre' => 'Costa Rica'                          ],
		['id' => 50	, 'nombre' => 'Cote d Ivoire'                       ],
		['id' => 51	, 'nombre' => 'Croatia'                             ],
		['id' => 52	, 'nombre' => 'Cuba'                                ],
		['id' => 53	, 'nombre' => 'Cyprus'                              ],
		['id' => 54	, 'nombre' => 'Czech Republic'                      ],
		['id' => 55	, 'nombre' => 'Denmark'                             ],
		['id' => 56	, 'nombre' => 'Djibouti'                            ],
		['id' => 57	, 'nombre' => 'Dominica'                            ],
		['id' => 58	, 'nombre' => 'Dominican Republic'                  ],
		['id' => 59	, 'nombre' => 'East Timor'                          ],
		['id' => 60	, 'nombre' => 'Ecuador'                             ],
		['id' => 61	, 'nombre' => 'Egypt'                               ],
		['id' => 62	, 'nombre' => 'El Salvador'                         ],
		['id' => 63	, 'nombre' => 'Equatorial Guinea'                   ],
		['id' => 64	, 'nombre' => 'Eritrea'                             ],
		['id' => 65	, 'nombre' => 'Estonia'                             ],
		['id' => 66	, 'nombre' => 'Ethiopia'                            ],
		['id' => 67	, 'nombre' => 'Faroe Islands'                       ],
		['id' => 68	, 'nombre' => 'Fiji'                                ],
		['id' => 69	, 'nombre' => 'Finland'                             ],
		['id' => 70	, 'nombre' => 'France'                              ],
		['id' => 71	, 'nombre' => 'French Guiana'                       ],
		['id' => 72	, 'nombre' => 'French Polynesia'                    ],
		['id' => 73	, 'nombre' => 'Gabon'                               ],
		['id' => 74	, 'nombre' => 'Gambia'                              ],
		['id' => 75	, 'nombre' => 'Gaza Strip'                          ],
		['id' => 76	, 'nombre' => 'Georgia'                             ],
		['id' => 77	, 'nombre' => 'Germany'                             ],
		['id' => 78	, 'nombre' => 'Ghana'                               ],
		['id' => 79	, 'nombre' => 'Gibraltar'                           ],
		['id' => 80	, 'nombre' => 'Greece'                              ],
		['id' => 81	, 'nombre' => 'Greenland'                           ],
		['id' => 82	, 'nombre' => 'Grenada'                             ],
		['id' => 83	, 'nombre' => 'Guadeloupe'                          ],
		['id' => 84	, 'nombre' => 'Guam'                                ],
		['id' => 85	, 'nombre' => 'Guatemala'                           ],
		['id' => 86	, 'nombre' => 'Guernsey'                            ],
		['id' => 87	, 'nombre' => 'Guinea'                              ],
		['id' => 88	, 'nombre' => 'Guinea-Bissau'                       ],
		['id' => 89	, 'nombre' => 'Guyana'                              ],
		['id' => 90	, 'nombre' => 'Haiti'                               ],
		['id' => 91	, 'nombre' => 'Honduras'                            ],
		['id' => 92	, 'nombre' => 'Hong Kong'                           ],
		['id' => 93	, 'nombre' => 'Hungary'                             ],
		['id' => 94	, 'nombre' => 'Iceland'                             ],
		['id' => 95	, 'nombre' => 'India'                               ],
		['id' => 96	, 'nombre' => 'Indonesia'                           ],
		['id' => 97	, 'nombre' => 'Iran'                                ],
		['id' => 98	, 'nombre' => 'Iraq'                                ],
		['id' => 99	, 'nombre' => 'Ireland'                             ],
		['id' => 100, 'nombre' => 'Isle of Man'                         ],
		['id' => 101, 'nombre' => 'Israel'                              ],
		['id' => 102, 'nombre' => 'Italy'                               ],
		['id' => 103, 'nombre' => 'Jamaica'                             ],
		['id' => 104, 'nombre' => 'Japan'                               ],
		['id' => 105, 'nombre' => 'Jersey'                              ],
		['id' => 106, 'nombre' => 'Jordan'                              ],
		['id' => 107, 'nombre' => 'Kazakhstan'                          ],
		['id' => 108, 'nombre' => 'Kenya'                               ],
		['id' => 109, 'nombre' => 'Kiribati'                            ],
		['id' => 110, 'nombre' => 'North Korea'                         ],
		['id' => 111, 'nombre' => 'South Kore'                          ],
		['id' => 112, 'nombre' => 'Kuwait'                              ],
		['id' => 113, 'nombre' => 'Kyrgyzstan'                          ],
		['id' => 114, 'nombre' => 'Laos'                                ],
		['id' => 115, 'nombre' => 'Latvia'                              ],
		['id' => 116, 'nombre' => 'Lebanon'                             ],
		['id' => 117, 'nombre' => 'Lesotho'                             ],
		['id' => 118, 'nombre' => 'Liberia'                             ],
		['id' => 119, 'nombre' => 'Libya'                               ],
		['id' => 120, 'nombre' => 'Liechtenstein'                       ],
		['id' => 121, 'nombre' => 'Lithuania'                           ],
		['id' => 122, 'nombre' => 'Luxembourg'                          ],
		['id' => 123, 'nombre' => 'Macau'                               ],
		['id' => 124, 'nombre' => 'Macedonia'                           ],
		['id' => 125, 'nombre' => 'Madagascar'                          ],
		['id' => 126, 'nombre' => 'Malawi'                              ],
		['id' => 127, 'nombre' => 'Malaysia'                            ],
		['id' => 128, 'nombre' => 'Maldives'                            ],
		['id' => 129, 'nombre' => 'Mali'                                ],
		['id' => 130, 'nombre' => 'Malta'                               ],
		['id' => 131, 'nombre' => 'Marshall Islands'                    ],
		['id' => 132, 'nombre' => 'Martinique'                          ],
		['id' => 133, 'nombre' => 'Mauritania'                          ],
		['id' => 134, 'nombre' => 'Mauritius'                           ],
		['id' => 135, 'nombre' => 'Mayotte'                             ],
		['id' => 136, 'nombre' => 'Mexico'                              ],
		['id' => 137, 'nombre' => 'Micronesia'                          ],
		['id' => 138, 'nombre' => 'Moldova'                             ],
		['id' => 139, 'nombre' => 'Monaco'                              ],
		['id' => 140, 'nombre' => 'Mongolia'                            ],
		['id' => 141, 'nombre' => 'Montserrat'                          ],
		['id' => 142, 'nombre' => 'Morocco'                             ],
		['id' => 143, 'nombre' => 'Mozambique'                          ],
		['id' => 144, 'nombre' => 'Namibia'                             ],
		['id' => 145, 'nombre' => 'Nauru'                               ],
		['id' => 146, 'nombre' => 'Nepal'                               ],
		['id' => 147, 'nombre' => 'Netherlands'                         ],
		['id' => 148, 'nombre' => 'Netherlands Antilles'                ],
		['id' => 149, 'nombre' => 'New Caledonia'                       ],
		['id' => 150, 'nombre' => 'New Zealand'                         ],
		['id' => 151, 'nombre' => 'Nicaragua'                           ],
		['id' => 152, 'nombre' => 'Niger'                               ],
		['id' => 153, 'nombre' => 'Nigeria'                             ],
		['id' => 154, 'nombre' => 'N. Mariana Islands'                  ],
		['id' => 155, 'nombre' => 'Norway'                              ],
		['id' => 156, 'nombre' => 'Oman'                                ],
		['id' => 157, 'nombre' => 'Pakistan'                            ],
		['id' => 158, 'nombre' => 'Palau'                               ],
		['id' => 159, 'nombre' => 'Panama'                              ],
		['id' => 160, 'nombre' => 'Papua New Guinea'                    ],
		['id' => 161, 'nombre' => 'Paraguay'                            ],
		['id' => 162, 'nombre' => 'Peru'                                ],
		['id' => 163, 'nombre' => 'Philippines'                         ],
		['id' => 164, 'nombre' => 'Poland'                              ],
		['id' => 165, 'nombre' => 'Portugal'                            ],
		['id' => 166, 'nombre' => 'Puerto Rico'                         ],
		['id' => 167, 'nombre' => 'Qatar'                               ],
		['id' => 168, 'nombre' => 'Reunion'                             ],
		['id' => 169, 'nombre' => 'Romania'                             ],
		['id' => 170, 'nombre' => 'Russia'                              ],
		['id' => 171, 'nombre' => 'Rwanda'                              ],
		['id' => 172, 'nombre' => 'Saint Helena'                        ],
		['id' => 173, 'nombre' => 'Saint Kitts & Nevis'                 ],
		['id' => 174, 'nombre' => 'Saint Lucia'                         ],
		['id' => 175, 'nombre' => 'St Pierre & Miquelon'                ],
		['id' => 176, 'nombre' => 'Saint Vincent and the Grenadines'    ],
		['id' => 177, 'nombre' => 'Samoa'                               ],
		['id' => 178, 'nombre' => 'San Marino'                          ],
		['id' => 179, 'nombre' => 'Sao Tome & Principe'                 ],
		['id' => 180, 'nombre' => 'Saudi Arabia'                        ],
		['id' => 181, 'nombre' => 'Senegal'                             ],
		['id' => 182, 'nombre' => 'Serbia'                              ],
		['id' => 183, 'nombre' => 'Seychelles'                          ],
		['id' => 184, 'nombre' => 'Sierra Leone'                        ],
		['id' => 185, 'nombre' => 'Singapore'                           ],
		['id' => 186, 'nombre' => 'Slovakia'                            ],
		['id' => 187, 'nombre' => 'Slovenia'                            ],
		['id' => 188, 'nombre' => 'Solomon Islands'                     ],
		['id' => 189, 'nombre' => 'Somalia'                             ],
		['id' => 190, 'nombre' => 'South Africa'                        ],
		['id' => 191, 'nombre' => 'Spain'                               ],
		['id' => 192, 'nombre' => 'Sri Lanka'                           ],
		['id' => 193, 'nombre' => 'Sudan'                               ],
		['id' => 194, 'nombre' => 'Suriname'                            ],
		['id' => 195, 'nombre' => 'Swaziland'                           ],
		['id' => 196, 'nombre' => 'Sweden'                              ],
		['id' => 197, 'nombre' => 'Switzerland'                         ],
		['id' => 198, 'nombre' => 'Syria'                               ],
		['id' => 199, 'nombre' => 'Taiwan'                              ],
		['id' => 200, 'nombre' => 'Tajikistan'                          ],
		['id' => 201, 'nombre' => 'Tanzania'                            ],
		['id' => 202, 'nombre' => 'Thailand'                            ],
		['id' => 203, 'nombre' => 'Togo'                                ],
		['id' => 204, 'nombre' => 'Tonga'                               ],
		['id' => 205, 'nombre' => 'Trinidad & Tobago'                   ],
		['id' => 206, 'nombre' => 'Tunisia'                             ],
		['id' => 207, 'nombre' => 'Turkey'                              ],
		['id' => 208, 'nombre' => 'Turkmenistan'                        ],
		['id' => 209, 'nombre' => 'Turks & Caicos Is'                   ],
		['id' => 210, 'nombre' => 'Tuvalu'                              ],
		['id' => 211, 'nombre' => 'Uganda'                              ],
		['id' => 212, 'nombre' => 'Ukraine'                             ],
		['id' => 213, 'nombre' => 'United Arab Emirates'                ],
		['id' => 214, 'nombre' => 'United Kingdom'                      ],
		['id' => 215, 'nombre' => 'United States'                       ],
		['id' => 216, 'nombre' => 'Uruguay'                             ],
		['id' => 217, 'nombre' => 'Uzbekistan'                          ],
		['id' => 218, 'nombre' => 'Vanuatu'                             ],
		['id' => 219, 'nombre' => 'Venezuela'                           ],
		['id' => 220, 'nombre' => 'Vietnam'                             ],
		['id' => 221, 'nombre' => 'Virgin Islands'                      ],
		['id' => 222, 'nombre' => 'Wallis and Futuna'                   ],
		['id' => 223, 'nombre' => 'West Bank'                           ],
		['id' => 224, 'nombre' => 'Western Sahara'                      ],
		['id' => 225, 'nombre' => 'Yemen'                               ],
		['id' => 226, 'nombre' => 'Zambia'                              ],
		['id' => 227, 'nombre' => 'Zimbabwe'                            ]
		]);
		
    }
	
}
